import * as ts from "typescript";
import { factory } from "typescript";

export const createShimRoot = (moduleNameSpaece: string) => [
  factory.createModuleDeclaration(
    undefined,
    [factory.createModifier(ts.SyntaxKind.DeclareKeyword)],
    factory.createStringLiteral(moduleNameSpaece),
    factory.createModuleBlock([
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("GetResBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("GetReqQuery"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("GetReqBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PostResBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PostReqQuery"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PostReqBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PutResBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PutReqQuery"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PutReqBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PatchResBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PatchReqQuery"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("PatchReqBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("DeleteResBody"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("DeleteReqQuery"),
        undefined,
        undefined,
        []
      ),
      factory.createInterfaceDeclaration(
        undefined,
        undefined,
        factory.createIdentifier("DeleteReqBody"),
        undefined,
        undefined,
        []
      ),
    ])
  ),
];
